# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

apiVersion: v1
kind: Pod
metadata:
  labels:
    service: oamservice
  name: oam
  namespace: ngc
spec:
  volumes:
  - name: shared-configs
    hostPath:
      path: /etc/openness/configs/ngc
  - name: shared-certs
    hostPath:
      path: /etc/openness/certs/ngc
  containers:
  - securityContext:
      privileged: false
    name: oam-container
    image: oam-image:1.0
    imagePullPolicy: Never
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "./entrypoint.sh" ]
    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi
    ports:
    - containerPort: 8070
    volumeMounts:
    - name: shared-configs
      mountPath: /root/configs
    - name: shared-certs
      mountPath: /etc/certs
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    5g-openness: "true"
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: oamservice
  labels:
    service: oamservice
  namespace: ngc
spec:
  type: NodePort
  ports:
  - port: 8070
    targetPort: 8070
    nodePort: 30070
    protocol: TCP
    name: oamcnca
  selector:
    service: oamservice

